---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .terragrunt-cache/
  .terraform/
  **/.terraform/*
  **/.terragrunt-cache/*
