name: Bug Report
description: Report an infrastructure issue or bug
title: "[BUG]: "
labels: ["bug", "triage"]
assignees:
  - Chopsticks13

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - dev
        - staging
        - prod
        - sandbox
        - multiple
    validations:
      required: true

  - type: input
    id: project
    attributes:
      label: Project ID
      description: Which GCP project is affected?
      placeholder: "e.g., dev-gcp-core"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `terragrunt plan` in...
        2. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant Terraform/Terragrunt logs
      render: shell
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Terraform version:
        - Terragrunt version:
        - Were there any recent changes?
    validations:
      required: false
