name: Feature Request
description: Suggest a new feature or enhancement for the infrastructure modules
title: "[FEATURE]: "
labels: ["enhancement", "triage"]
assignees:
  - Chopsticks13

body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request

        Suggest a new feature or enhancement to the GCP foundation modules.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Terraform Module
        - Enhancement to Existing Module
        - CI/CD Pipeline Improvement
        - Documentation
        - Tooling/Automation
        - Other
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module does this relate to?
      options:
        - gcp-project
        - New Module
        - Multiple Modules
        - Not Module-Specific
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, we cannot... This causes..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: "I've considered X, but..."
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Usage Example
      description: Show how you envision using this feature
      placeholder: |
        ```hcl
        module "example" {
          source = "..."
          // your example here
        }
        ```
      render: hcl
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking work
        - Critical - Urgent need
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have considered if this could be implemented outside the core modules
          required: false
